name: gradle build test caching docker image temp

on:
  workflow_dispatch:

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  ktlint-check:
    needs: [set-up]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grand execute permission for gradlew
        run: chmod +x gradlew
      - name: ktlint check
        run: ./gradlew clean ktlintCheck
  run-test:
    needs: [set-up]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grand execute permission for gradlew
        run: chmod +x gradlew
      - name: Load mysql and redis image in cache
        run: |
          docker pull redis:7.0.7
          docker pull mysql:8.0
      - name: execute test
        run: ./gradlew clean test --debug
  complete:
    needs: [ktlint-check, run-test]
    runs-on: ubuntu-latest
    steps:
      - name: echo complete
        run: echo "complete"
