name: gradle build test with module

on:
  workflow_dispatch:

env:
  MYSQL_VERSION: '8.0'
  JAVA_VERSION: '17'
  DISTRIBUTION: 'temurin'

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/caching-docker-image
        with:
          MYSQL_VERSION: ${{ env.MYSQL_VERSION }}
  ktlint-check:
    needs: [set-up]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ktlint-check
        with:
          JAVA_VERSION: ${{ env.JAVA_VERSION }}
          DISTRIBUTION: ${{ env.DISTRIBUTION }}
  run-test:
    needs: [set-up]
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/run-test
        with:
          JAVA_VERSION: ${{ env.JAVA_VERSION }}
          DISTRIBUTION: ${{ env.DISTRIBUTION }}
  complete:
    needs: [ktlint-check, run-test]
    runs-on: ubuntu-latest
    steps:
      - name: echo complete
        run: echo "complete"
